### ISSUE TITLE
Run script error: not logged in

### ISSUE THREAD

**Issue by ebendl** [pilotak/homeassistant-mikrotik#7]
I loaded the custom component and set up a user with a password and added it to my configuration:

```
mikrotik:
    host: 172.16.16.1
    username: !secret mikrotik_user
    password: !secret mikrotik_pass
```
I start Home Assistant and the log is clean. However whenever I try to run any service I get this message in the HA log:

![image](https://user-images.githubusercontent.com/52312239/112221646-5bb77280-8c30-11eb-8633-fe972d7c828f.png)

> Logger: custom_components.mikrotik
> Source: custom_components/mikrotik/__init__.py:139
> Integration: Mikrotik
> First occurred: 23:33:28 (11 occurrences)
> Last logged: 23:33:33
> 
> Run script error: not logged in

I've checked my Mikrotik's log -- I don't see any message indicating that someone tried to log in. Should I be doing something additional?

**Comment by pilotak** [comment]
could you please turn on the debugging?

are you using default port 8728? and user exists with proper privileges?

```yaml
logger:
 default: warning
 logs:
  custom_components.mikrotik: debug
```
