### ISSUE TITLE
Failed to call mikrotik.api

### ISSUE THREAD

**Issue by rzemykers** [pilotak/homeassistant-mikrotik#8]
I'm new in HA and probably i'm doing something wrong.
![ha-mikrotik](https://user-images.githubusercontent.com/18058558/131249729-2d8aaa59-03c7-44c2-b26f-44f9e6d90df3.png)

Files are existing in custom_components/mikrotik
![ha-mikrotik-02](https://user-images.githubusercontent.com/18058558/131250033-b17df0c8-10bc-459a-8552-4517cb365904.png)

please help.

**Comment by pilotak** [comment]
Have you set this up?
```yaml
# Example configuration.yaml entry
mikrotik:
  host: IP here
  username: user
  password: password

```
